name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  # Déployer sur la VM ubuntu de gh-page avec node
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # Intaller les dépendances et faire le build de l'app
      - name: Install dependencies
        run: npm install --frozen-lockfile
      - name: Build website
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # Token généré automatiquement
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build l'app dans ce dossier
          publish_dir: ./dist/rick_a_card
          # Bot pour deployer automatiquement
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
